version: '3.8'
services:
  api:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - KML_FIELDS_PATH=Data/fields.kml
      - KML_CENTROIDS_PATH=Data/centroids.kml
    volumes:
      - ./Data:/app/Data
